//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GATAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleanup
    {
        public long CleanupId { get; set; }
        public long UserId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long SourceId { get; set; }
        public int Hits { get; set; }
        public int Deleted { get; set; }
    
        public virtual Source Source { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
