//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GATAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleanup
    {
        public long CleanupId { get; set; }
        public long UserId { get; set; }
        public bool LocalDisk { get; set; }
        public int LocalDiskResults { get; set; }
        public int LocalDiskDeleted { get; set; }
        public bool Email { get; set; }
        public int EmailResults { get; set; }
        public int EmailDeleted { get; set; }
        public bool Teams { get; set; }
        public int TeamsResults { get; set; }
        public int TeamsDeleted { get; set; }
        public bool Skype { get; set; }
        public int SkypeResults { get; set; }
        public int SkypeDeleted { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
