//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GATAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GatEntities : DbContext
    {
        public GatEntities()
            : base("name=GatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Keyword> Keyword { get; set; }
        public virtual DbSet<KeywordList> KeywordList { get; set; }
        public virtual DbSet<Cleanup> Cleanup { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Source> Source { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<UserFinishedSchedule> UserFinishedSchedule { get; set; }
    }
}
