//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GATAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeywordList
    {
        public long KeywordListId { get; set; }
        public long KeywordId { get; set; }
    
        public virtual Keyword Keyword { get; set; }
    }
}
