//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GATAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFinishedSchedule
    {
        public long UserId { get; set; }
        public long ScheduleId { get; set; }
        public System.DateTime FinishedAt { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
